// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdminWebsite.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Case Admin saves booking and views confirmation screen")]
    public partial class CaseAdminSavesBookingAndViewsConfirmationScreenFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BookingConfirmation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Case Admin saves booking and views confirmation screen", "As a Case Admin\r\nI want to confirm the booking and see a confirmation of the book" +
                    "ing\r\nSo that the hearing can take place on the time and date specified", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Case Admin creates hearing with an existing individual")]
        [NUnit.Framework.CategoryAttribute("VIH-2701")]
        [NUnit.Framework.CategoryAttribute("ExistingPerson")]
        [NUnit.Framework.CategoryAttribute("smoketest")]
        public virtual void CaseAdminCreatesHearingWithAnExistingIndividual()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Case Admin creates hearing with an existing individual", null, new string[] {
                        "VIH-2701",
                        "ExistingPerson",
                        "smoketest"});
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("Case Admin is on Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("user submit booking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then("hearing should be booked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Case Admin with multiple case types saves booking")]
        [NUnit.Framework.CategoryAttribute("VIH-2701")]
        [NUnit.Framework.CategoryAttribute("bug")]
        [NUnit.Framework.TestCaseAttribute("Civil Money Claims", "Claimant", "Claimant LIP", null)]
        [NUnit.Framework.TestCaseAttribute("Civil Money Claims", "Defendant", "Defendant LIP", null)]
        [NUnit.Framework.TestCaseAttribute("Civil Money Claims", "Defendant", "Solicitor", null)]
        [NUnit.Framework.TestCaseAttribute("Financial Remedy", "Applicant", "Applicant LIP", null)]
        [NUnit.Framework.TestCaseAttribute("Financial Remedy", "Respondent", "Respondent LIP", null)]
        [NUnit.Framework.TestCaseAttribute("Financial Remedy", "Respondent", "Solicitor", null)]
        public virtual void CaseAdminWithMultipleCaseTypesSavesBooking(string caseTypes, string party, string role, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "VIH-2701",
                    "bug"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Case Admin with multiple case types saves booking", null, @__tags);
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 14
 testRunner.Given(string.Format("\'VH Officer\' with {0} adds participant with {1} and {2} to booking", caseTypes, party, role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.When("user submit booking", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("hearing should be booked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
