# Set variables once
variables:
  cleanChekout: 'false'
  solutionType: angularDotNetCore # angularDotNetCore, dotNetCore
  apiDirectory: 'AdminWebsite/AdminWebsite'
  sonarCloudPrepareExtraProperties: |
    sonar.exclusions=**/node_modules/**,**/*.spec.ts,*.spec.ts,**/ClientApp/src/*,**/ClientApp/coverage/**/*
    sonar.typescript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/AdminWebsite/AdminWebsite/ClientApp/coverage/lcov.info
    sonar.typescript.exclusions=**/node_modules/**,**/typings.d.ts,**/main.ts,**/environments/environment*.ts,**/*routing.module.ts,**/api-client.ts
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions=**/Testing.Common/**,AdminWebsite/Views/*,AdminWebsite/Pages/*,AdminWebsite.UserAPI.Client/*,AdminWebsite.AcceptanceTests/*
  nodeVersion: 10.16.0
  integrationTestsAppSettingsTransform: '
  "AzureAd/Authority":"https://login.microsoftonline.com/$(TenantId)",
  "AzureAd/ClientId":"$(vh-admin-web-appid)",
  "AzureAd/ClientSecret":"$(vh-admin-web-key)",
  "AzureAd:TenantId":"$(TenantId)",
  "VhServices/BookingsApiResourceId":"$(vh-bookings-api-identifieruris)",
  "VhServices/UserApiResourceId":"$(vh-user-api-identifieruris)"'

  vhAzureKeyVault: 'https://vhwebsitepreview.vault.azure.net/' # Used during integration tests
  keyVaultName: vhcoreinfrahtpreview # Used to get secrets for integration tests
  secretsFilter: 'TenantId,vh-admin-web-appid,vh-admin-web-key,vh-bookings-api-identifieruris,vh-user-api-identifieruris' # filters out secrets returned from key vault
  infraKeyVaultName: 'vhcoreinfradev'
  infraSecretsFilter: 'vh-core-infra-AppInsightsKey'
  dotnetVersion: 3.1

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    endpoint: 'GitHubDevOps'

trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*
pr:
  - '*'

jobs:
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    cleanCheckout: $(cleanCheckout)
    sonarCloudExtraProperties: $(sonarCloudPrepareExtraProperties)
    KeyVaultName: $(KeyVaultName)
    apiDirectory: $(apiDirectory)
    SecretsFilter: $(SecretsFilter)
    solutionType: $(solutionType)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    infraKeyVaultName: $(infraKeyVaultName)
    infraSecretsFilter: $(infraSecretsFilter)
    nodeVersion: $(nodeVersion)
    dotNetCoreVersion: $(dotnetVersion)
