parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: Sandbox
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Demo
  - Preprod
  - Prod

- name: RunZap
  displayName: Execute ZAP Tests
  type: boolean
  default: false

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-admin-web
  - group: vh test users
  - group: Saucelabs
  - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
    - group: vh-prod
  - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
    - group: vh-preview

trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts (1)
  pipelines:
  - pipeline: CI
    source: hmcts.vh-admin-web
    trigger: 
      branches:
      - master
      - hotfix/*
      - release/*

stages:
  - template: templates/vh-release.yml@templates
    parameters:
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        environments:
          - ${{ parameters.environment }}
        deploymentBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deploymentBranch: $(resources.pipeline.CI.sourceBranch)
      releaseParameters:
        runZapTests: ${{ parameters.RunZap }}
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_admin_web
        deploymentSlot: production
        appName: vh-admin-web-$(environment)
        resourceGroup: vh-admin-web-$(environment)
        testCaseFilter: TestCategory=smoketest
        dependentApps:
        - vh-user-api-$(environment)
        - vh-bookings-api-$(environment)
        - vh-video-api-$(environment)
        variables:
          - group: vh-wowza-dev
            env:
             - Preview
             - Dev
             - AAT
             - Sandbox
             - Test1
             - Test2
          - group: vh-wowza-demo
            env:
             - Demo
          - group: vh-wowza-preprod
            env:
             - Preprod
          - group: vh-wowza-prod
            env:
             - Prod
          - group: KinlyConfiguration_Test
            env:
             - Preview
             - Dev
             - AAT
             - Sandbox
             - Test1
             - Test2
          - group: KinlyConfiguration_Test2
            env:
             - Demo
          - group: KinlyConfiguration_Preprod
            env:
             - Preprod
          - group: KinlyConfiguration_Prod
            env:
             - Prod
        appSettings:
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AppInsightsKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: IsLive
            value: $(IsLive)

          # AzureAd
          - name: AzureAd:Authority
            value: $(Authority)
          - name: AzureAd:BaseVideoUrl
            value: $(video_blob_url)
          - name: AzureAd:ClientId
            value: vh-service-web-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-service-web-key
            secret: true
          - name: AzureAd:PostLogoutRedirectUri
            slot:
              deployment:
                value: $(service_web_url_staging)logout
              active:
                value: $(service_web_url)logout
          - name: AzureAd:RedirectUri
            slot:
              deployment:
                value: $(service_web_url_staging)
              active:
                value: $(service_web_url)
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:UserApiClientId
            value: vh-user-api-appid
            secret: true
          - name: AzureAd:UserApiClientSecret
            value: vh-user-api-key
            secret: true

          # Kinly
          - name: KinlyConfiguration:CallbackSecret
            value: $(CallbackKey)
          - name: KinlyConfiguration:ApiSecret
            value: $(KinlyApiKey)
          - name: KinlyConfiguration:SelfTestApiSecret
            value: $(SelfTestApiKey)

          # Testing
          - name: TestUserSecrets:TestUsernameStem
            value: $(TestUserSecrets:TestUsernameStem)
          - name: TestUserSecrets:TestUserPassword
            value: $(TestUserSecrets:TestUserPassword)

          # VhServices
          - name: VhServices:BookingsApiResourceId
            value: vh-bookings-api-identifieruris
            secret: true
          - name: VhServices:BookingsApiUrl
            value: $(bookings_api_url)
          - name: VhServices:UserApiResourceId
            value: vh-user-api-identifieruris
            secret: true
          - name: VhServices:UserApiUrl
            value: $(user_api_url)
          - name: VhServices:VideoApiResourceId
            value: vh-video-api-identifieruris
            secret: true
          - name: VhServices:VideoApiUrl
            value: $(video_api_url)
          - name: VhServices:VideoWebUrl
            value: $(video_web_url)
          - name: VhServices:KinlySelfTestScoreEndpointUrl
            value: $(KinlySelfTestApiUrl)/testcall
          - name: VhServices:PexipSelfTestNodeUri
            value: $(PexipSelfTestNode)
          - name: VhServices:ServiceWebUrl
            slot:
              deployment:
                value: $(service_web_url_staging)
              active:
                value: $(service_web_url)
        acceptanceTestSettings:
          # AzureAd
          - name: AzureAd:AppInsightsKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AzureAd:Authority
            value: $(Authority)
          - name: AzureAd:BaseVideoUrl
            value: $(video_blob_url)
          - name: AzureAd:ClientId
            value: vh-service-web-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-service-web-key
            secret: true
          - name: AzureAd:PostLogoutRedirectUri
            slot: true
          - name: AzureAd:RedirectUri
            slot: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:UserApiClientId
            value: vh-user-api-appid
            secret: true
          - name: AzureAd:UserApiClientSecret
            value: vh-user-api-key
            secret: true

          # Kinly
          - name: KinlyConfiguration:CallbackSecret
            value: $(CallbackKey)
          - name: KinlyConfiguration:ApiSecret
            value: $(KinlyApiKey)
          - name: KinlyConfiguration:SelfTestApiSecret
            value: $(SelfTestApiKey)

          # Testing
          - name: TestUserSecrets:TestUsernameStem
            value: $(TestUserSecrets:TestUsernameStem)
          - name: TestUserSecrets:TestUserPassword
            value: $(TestUserSecrets:TestUserPassword)

          # VhServices
          - name: VhServices:BookingsApiResourceId
            value: vh-bookings-api-identifieruris
            secret: true
          - name: VhServices:BookingsApiUrl
            value: $(bookings_api_url)
          - name: VhServices:UserApiResourceId
            value: vh-user-api-identifieruris
            secret: true
          - name: VhServices:UserApiUrl
            value: $(user_api_url)
          - name: VhServices:VideoApiResourceId
            value: vh-video-api-identifieruris
            secret: true
          - name: VhServices:VideoApiUrl
            value: $(video_api_url)
          - name: VhServices:VideoWebUrl
            value: $(video_web_url)
          - name: VhServices:KinlySelfTestScoreEndpointUrl
            value: $(KinlySelfTestApiUrl)/testcall
          - name: VhServices:PexipSelfTestNodeUri
            value: $(PexipSelfTestNode)
          - name: VhServices:ServiceWebUrl
            slot: true

          # SauceLabs
          - name: Saucelabs:Username
            value: $(Saucelabs:Username)
          - name: Saucelabs:AccessKey
            value: $(Saucelabs:AccessKey)
          - name: Saucelabs:RealDeviceApiKey
            value: $(RealDeviceApiKey)
