name: $(Date:yyyyMMddHHmm)-$(Rev:r)

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: VIH-0000-Test-Dotnet-Branch
      endpoint: hmcts

pool:
  vmImage: ubuntu-22.04

trigger: none

pr: none

variables:
  - group: vh-github-app-credentials
  - group: vh-admin-web
  - name: run_acceptance_tests
    value: false

jobs:
  - job: UnitAndIntegrationTests
    displayName: Unit and Integration Tests
    steps:
      - task: AzureCLI@2
        displayName: Run Unit & Integration Tests
        inputs:
          scriptType: pscore
          scriptLocation: 'inlineScript'
          inlineScript: |
            $dockerComposeTestFile = "docker-compose.test.yml"
            $repositoryName = $("Build.Repository.Name")
            $dockerComposeCommand = "up"
            $arguments = "--build --abort-on-container-exit"

            Write-Host "Running Unit & Integration Tests using Docker Compose"
            $command = "docker-compose -f $dockerComposeTestFile -p $repositoryName $dockerComposeCommand $arguments"
            Write-Host "Executing: $command"
            Invoke-Expression $command
