# Set variables once
variables:
  - group: vh-admin-web
  - name: cleanChekout
    value: false
  - name: solutionType
    value: angularDotNetCore # angularDotNetCore, dotNetCore
  - name: apiDirectory
    value: 'AdminWebsite/AdminWebsite'
  - name: sonarCloudPrepareExtraProperties
    value: |
    sonar.exclusions=**/node_modules/**, **/*.spec.ts, *.spec.ts, **/ClientApp/src/*, **/ClientApp/coverage/**/*, **/Startup.cs, **/Program.cs, **/ConfigureServicesExtensions.cs, **/Swagger/*.cs
    sonar.typescript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/AdminWebsite/AdminWebsite/ClientApp/coverage/lcov.info
    sonar.typescript.exclusions=**/node_modules/**, **/typings.d.ts, **/main.ts, **/environments/environment*.ts, **/*routing.module.ts, **/api-client.ts
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions= **/Testing.Common/**, AdminWebsite/Views/*, AdminWebsite/Pages/*, AdminWebsite.UserAPI.Client/*, AdminWebsite.AcceptanceTests/*
  - name: nodeVersion
    value: 10.16.0
  - name: integrationTestsAppSettingsTransform
    value: |
      "AzureAd/Authority":"https://login.microsoftonline.com/$(TenantId)",
      "AzureAd/ClientId":"$(vh-admin-web-appid)",
      "AzureAd/ClientSecret":"$(vh-admin-web-key)",
      "AzureAd/TenantId":"$(TenantId)",
      "VhServices/BookingsApiResourceId":"$(vh-bookings-api-identifieruris)",
      "VhServices/UserApiResourceId":"$(vh-user-api-identifieruris)",
      "VhServices/ValidateEmail":"$(reformemail)"
  - name: vhAzureKeyVault
    value: 'https://vhwebsitepreview.vault.azure.net/' # Used during integration tests
  - name: keyVaultName
    value: vhcoreinfrahtpreview # Used to get secrets for integration tests
  - name: secretsFilter
    value: 'TenantId,vh-admin-web-appid,vh-admin-web-key,vh-bookings-api-identifieruris,vh-user-api-identifieruris' # filters out secrets returned from key vault
  - name: infraKeyVaultName
    value: 'vhcoreinfradev'
  - name: infraSecretsFilter
    value: 'vh-core-infra-AppInsightsKey'
  - name: dotnetVersion
    value: 2.2.207

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    endpoint: hmcts

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*
pr:
  - master

jobs:
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    cleanCheckout: $(cleanCheckout)
    sonarCloudExtraProperties: $(sonarCloudPrepareExtraProperties)
    KeyVaultName: $(KeyVaultName)
    apiDirectory: $(apiDirectory)
    SecretsFilter: $(SecretsFilter)
    solutionType: $(solutionType)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    infraKeyVaultName: $(infraKeyVaultName)
    infraSecretsFilter: $(infraSecretsFilter)
    nodeVersion: $(nodeVersion)
    dotNetCoreVersion: $(dotnetVersion)
