parameters:
- name: PackageApp
  displayName: Package App
  type: boolean
  default: true

- name: PackageACTests
  displayName: Package Acceptance Tests
  type: boolean
  default: true

- name: RunUnitTests
  displayName: Run Unit Tests
  type: boolean
  default: true

- name: RunIntegTests
  displayName: Run Integration Tests
  type: boolean
  default: true

- name: RunSonarCloudTests
  displayName: Run Sonar Cloud Analysis
  type: boolean
  default: true

- name: RunMutationTests
  displayName: Run Mutation Tests
  type: boolean
  default: true

- name: RunACTests
  displayName: Run Acceptance Tests
  type: boolean
  default: true

- name: RunNodeTests
  displayName: Run Node Tests
  type: boolean
  default: true

- name: testSettings
  type: object
  default:
  # VhServices
  - name: VhServices:AdminWebUrl
    value: $(admin_web_url_staging)
  - name: VhServices:AdminWebResourceId
    value: vh-admin-web-identifieruris
    secret: true
  - name: VhServices:VideoApiUrl
    value: $(video_api_url)
  - name: VhServices:VideoApiResourceId
    value: vh-video-api-identifieruris
    secret: true
  - name: VhServices:UserApiUrl
    value: $(user_api_url)
  - name: VhServices:UserApiResourceId
    value: vh-user-api-identifieruris
    secret: true
  - name: VhServices:NotificationApiUrl
    value: $(notification_api_url)
  - name: VhServices:NotificationApiResourceId
    value: vh-notification-api-identifieruris
    secret: true
  - name: VhServices:TestApiUrl
    value: $(test_api_url)
  - name: VhServices:TestApiResourceId
    value: vh-test-api-identifieruris
    secret: true    
  - name: VhServices:BookingsApiUrl
    value: $(bookings_api_url)
  - name: VhServices:BookingsApiResourceId
    value: vh-bookings-api-identifieruris
    secret: true
  - name: VhServices:VideoWebUrl
    value: $(video_web_url)



  # GOV Notify Configuration
  - name: NotifyConfiguration:ApiKey
    value: $(notify-api-key)
    
  # AzureAd
  - name: AzureAd:TenantId
    value: tenantid
    secret: true
  - name: AzureAd:ClientId
    value: vh-video-web-appid-v2
    secret: true
  - name: AzureAd:ClientSecret
    value: vh-video-web-key-v2
    secret: true
  - name: AzureAd:PostLogoutRedirectUri
    slot: true
  - name: AzureAd:RedirectUri
    slot: true
  - name: AzureAd:TemporaryPassword
    value: $(TemporaryPassword)

  # Testing
  - name: TestUserSecrets:TestUsernameStem
    value: $(TestUserSecrets:TestUsernameStem)
  - name: TestUserSecrets:TestUserPassword
    value: $(TestUserSecrets:TestApiUserPassword)

    # Kinly
  - name: KinlyConfiguration:ConferencePhoneNumber
    value: $(ConferencePhoneNumber)
  - name: KinlyConfiguration:JoinByPhoneFromDate
    value: $(JoinByPhoneFromDate)
    
  # SauceLabs
  - name: Saucelabs:Username
    value: $(Saucelabs:Username)
  - name: Saucelabs:AccessKey
    value: $(Saucelabs:AccessKey)
  - name: Saucelabs:RealDeviceApiKey
    value: $(RealDeviceApiKey)

  # WowzaConfiguration
  - name: WowzaConfiguration:StorageAccountName
    value: $(wowza_storageAccountName)
  - name: WowzaConfiguration:StorageAccountKey
    value: $(wowza_storageAccountKey)
  - name: WowzaConfiguration:StorageContainerName
    value: $(wowza_storageContainerName)
    
  # Ejud - test setting only
  - name: UsingEjud
    value: $(UsingEjud)

- name: appSettings
  type: object
  default:
  - name: ApplicationInsights:InstrumentationKey
    value: vh-core-infra-AppInsightsKey
    secret: true
  - name: AppInsightsKey
    value: vh-core-infra-AppInsightsKey
    secret: true
  - name: IsLive
    value: $(IsLive)

  # AzureAd
  - name: AzureAd:ClientId
    value: vh-admin-web-appid-v2
    secret: true
  - name: AzureAd:ClientSecret
    value: vh-admin-web-key-v2
    secret: true
  - name: AzureAd:PostLogoutRedirectUri
    slot:
      deployment:
        value: $(admin_web_url_staging)logout
      active:
        value: $(admin_web_url)logout
  - name: AzureAd:RedirectUri
    slot:
      deployment:
        value: $(admin_web_url_staging)home
      active:
        value: $(admin_web_url)home
  - name: AzureAd:TenantId
    value: tenantid
    secret: true
    
  # Testing
  - name: TestUserSecrets:TestUsernameStem
    value: $(TestUserSecrets:TestUsernameStem)

  # VhServices
  - name: VhServices:BookingsApiResourceId
    value: vh-bookings-api-identifieruris
    secret: true
  - name: VhServices:BookingsApiUrl
    value: $(bookings_api_url)
  - name: VhServices:UserApiResourceId
    value: vh-user-api-identifieruris
    secret: true
  - name: VhServices:UserApiUrl
    value: $(user_api_url)
  - name: VhServices:VideoApiResourceId
    value: vh-video-api-identifieruris
    secret: true
  - name: VhServices:VideoApiUrl
    value: $(video_api_url)
  - name: VhServices:NotificationApiUrl
    value: $(notification_api_url)
  - name: VhServices:NotificationApiResourceId
    value: vh-notification-api-identifieruris
    secret: true
  - name: VhServices:VideoWebUrl
    value: $(video_web_url)

  # GOV Notify Configuration
  - name: NotifyConfiguration:ApiKey
    value: $(notify-api-key)
    
  # Kinly
  - name: KinlyConfiguration:ConferencePhoneNumber
    value: $(ConferencePhoneNumber)
  - name: KinlyConfiguration:JoinByPhoneFromDate
    value: $(JoinByPhoneFromDate)
    
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-admin-web
  - group: vh-preview
  - group: vh test users
  - group: Saucelabs
  - group: vh-wowza-dev
  - group: KinlyConfiguration_Test
  - group: govuk-notify-preview

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*
pr:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: VIH-8168
      #ref: refs/heads/master
      endpoint: hmcts
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet-angular:3.1.102
    endpoint: sspublicsbox
  - container: dotnetsdk-cipipeline
    image: sspublicsbox.azurecr.io/vh/dotnet-angular-cipipeline:3.1.102
    endpoint: sspublicsbox
  - container: node
    image: node:lts-alpine

extends:
  template: stages\dotnet-package.yml@templates
  parameters:
    buildConfiguration: Debug
    useNugetConfig: false
    nugetConfigPath: AdminWebsite
    coreProjectPath: AdminWebsite/AdminWebsite
    nodeProjectPath: AdminWebsite/AdminWebsite/ClientApp
    PackageApp: ${{ parameters.PackageApp }}
    PackageAcceptanceTests: ${{ parameters.PackageACTests }}
    Test: ${{ or(parameters.RunUnitTests, parameters.RunIntegTests, parameters.RunMutationTests) }}
    testParameters:
      useNugetConfig: false
      nugetConfigPath: AdminWebsite
      coreProjectPath: AdminWebsite/AdminWebsite
      nodeProjectPath: AdminWebsite/AdminWebsite/ClientApp
      RunNode: true
      unitTestProjectPath: AdminWebsite/AdminWebsite.UnitTests
      integTestProjectPath: AdminWebsite/AdminWebsite.IntegrationTests
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      RunUnitTests: ${{ parameters.RunUnitTests }}
      RunIntegrationTests: ${{ parameters.RunIntegTests }}
      RunSonarCloud: ${{ parameters.RunSonarCloudTests }}
      RunStryker: ${{ parameters.RunMutationTests }}
      IntegrationTestSettings:
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
      coverletCoverageExclusions:
        - "**/Testing.Common/**"
        - "AdminWebsite/Views/*"
        - "AdminWebsite/Pages/*"
        - "AdminWebsite.UserAPI.Client/*"
        - "AdminWebsite.AcceptanceTests/*"
      sonarCloud_ExtraProperties: |
        sonar.exclusions=**/node_modules/**, **/*.spec.ts, *.spec.ts, **/ClientApp/src/*, **/ClientApp/coverage/**/*, **/Startup.cs, **/Program.cs, **/ConfigureServicesExtensions.cs, **/Swagger/*.cs
        sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/AdminWebsite/AdminWebsite/ClientApp/coverage/lcov.info
        sonar.typescript.exclusions=**/node_modules/**, **/typings.d.ts, **/main.ts, **/environments/environment*.ts, **/*routing.module.ts, **/api-client.ts
        sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/Coverage/coverage.opencover.xml
        sonar.coverage.exclusions= **/AdminWebsite/Models/**, **/AdminWebsite.Testing.Common/**, AdminWebsite/Views/*, AdminWebsite/Pages/*, AdminWebsite.UserAPI.Client/*, AdminWebsite.AcceptanceTests/*
    ACTest: ${{ parameters.RunACTests }}
    releaseParameters:
      environment: Preview
      subscription: $(pr_Subscription)
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      devOpsResource: vh_admin_web
      appName: vh-admin-web-$(environment)
      resourceGroup: vh-admin-web-$(environment)
      appSettings: ${{ parameters.appSettings }}
      testCaseFilter: TestCategory=Smoketest
      dependentApps:
        - name: vh-user-api-$(environment)
          resourceGroup: vh-user-api-$(environment)
          healthEndpoint: $(user_api_url)healthcheck/health
        - name: vh-bookings-api-$(environment)
          resourceGroup: vh-bookings-api-$(environment)
          healthEndpoint: $(bookings_api_url)healthcheck/health
        - name: vh-video-api-$(environment)
          resourceGroup: vh-video-api-$(environment)
          healthEndpoint: $(video_api_url)healthcheck/health
        - name: vh-notification-api-$(environment)
          resourceGroup: vh-notification-api-$(environment)
          healthEndpoint: $(notification_api_url)healthcheck/health
        - name: vh-test-api-$(environment)
          resourceGroup: vh-test-api-$(environment)
          healthEndpoint: $(test_api_url)health/health
      acceptanceTestSettings:
        - name: WebsiteUrl
          value: $(admin_web_url_staging)
        - ${{ each setting in parameters.testSettings }}:
          - ${{ insert }}: ${{ setting }}