/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.0.14.0 (NJsonSchema v9.13.18.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const BH_API_BASE_URL = new InjectionToken<string>('BH_API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class BHClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(BH_API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5300";
    }

    /**
     * Gets list of all submitted participant checklists including participant and hearing details.
    Ordered by checklist submission date, most recent checklist first.
     * @param pageSize (optional) Maximum number of items to retrieve in the page, maximum allowed 1000.
     * @param page (optional) One-based index of page to retrieve.
     * @return Success
     */
    getAllParticipantsChecklists(pageSize: number | null | undefined, page: number | null | undefined): Observable<ChecklistsResponse> {
        let url_ = this.baseUrl + "/api/checklists?";
        if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&"; 
        if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAllParticipantsChecklists(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllParticipantsChecklists(<any>response_);
                } catch (e) {
                    return <Observable<ChecklistsResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<ChecklistsResponse>><any>_observableThrow(response_);
        }));
    }

    protected processGetAllParticipantsChecklists(response: HttpResponseBase): Observable<ChecklistsResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? ChecklistsResponse.fromJS(resultData200) : new ChecklistsResponse();
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ChecklistsResponse>(<any>null);
    }

    /**
     * Get the configuration settings for client
     * @return Success
     */
    getConfigSettings(): Observable<ClientSettingsResponse> {
        let url_ = this.baseUrl + "/api/config";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetConfigSettings(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetConfigSettings(<any>response_);
                } catch (e) {
                    return <Observable<ClientSettingsResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<ClientSettingsResponse>><any>_observableThrow(response_);
        }));
    }

    protected processGetConfigSettings(response: HttpResponseBase): Observable<ClientSettingsResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? ClientSettingsResponse.fromJS(resultData200) : new ClientSettingsResponse();
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ClientSettingsResponse>(<any>null);
    }

    /**
     * Gets the all upcoming bookings hearing by the given case types for a hearing administrator.
     * @param cursor (optional) The unique sequential value of hearing ID.
     * @param limit (optional) The max number of hearings to be returned.
     * @return Success
     */
    getBookingsList(cursor: string | null | undefined, limit: number | null | undefined): Observable<BookingsResponse> {
        let url_ = this.baseUrl + "/api/hearings?";
        if (cursor !== undefined)
            url_ += "cursor=" + encodeURIComponent("" + cursor) + "&"; 
        if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetBookingsList(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetBookingsList(<any>response_);
                } catch (e) {
                    return <Observable<BookingsResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<BookingsResponse>><any>_observableThrow(response_);
        }));
    }

    protected processGetBookingsList(response: HttpResponseBase): Observable<BookingsResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? BookingsResponse.fromJS(resultData200) : new BookingsResponse();
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<BookingsResponse>(<any>null);
    }

    /**
     * Create a hearing
     * @param hearingRequest (optional) Hearing Request object
     * @return Success
     */
    bookNewHearing(hearingRequest: HearingRequest | null | undefined): Observable<number> {
        let url_ = this.baseUrl + "/api/hearings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(hearingRequest);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBookNewHearing(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBookNewHearing(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processBookNewHearing(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = resultData201 !== undefined ? resultData201 : <any>null;
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result400);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }

    /**
     * Gets a list hearing types
     * @return Success
     */
    getHearingTypes(): Observable<HearingTypeResponse[]> {
        let url_ = this.baseUrl + "/api/reference/types";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetHearingTypes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetHearingTypes(<any>response_);
                } catch (e) {
                    return <Observable<HearingTypeResponse[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<HearingTypeResponse[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetHearingTypes(response: HttpResponseBase): Observable<HearingTypeResponse[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HearingTypeResponse.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<HearingTypeResponse[]>(<any>null);
    }

    /**
     * Gets a list of hearing mediums
     * @return Success
     */
    getHearingMediums(): Observable<HearingMediumResponse[]> {
        let url_ = this.baseUrl + "/api/reference/mediums";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetHearingMediums(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetHearingMediums(<any>response_);
                } catch (e) {
                    return <Observable<HearingMediumResponse[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<HearingMediumResponse[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetHearingMediums(response: HttpResponseBase): Observable<HearingMediumResponse[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HearingMediumResponse.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<HearingMediumResponse[]>(<any>null);
    }

    /**
     * Get available participant roles
     * @return Success
     */
    getParticipantRoles(): Observable<ParticipantRoleResponse[]> {
        let url_ = this.baseUrl + "/api/reference/participantroles";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetParticipantRoles(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetParticipantRoles(<any>response_);
                } catch (e) {
                    return <Observable<ParticipantRoleResponse[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<ParticipantRoleResponse[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetParticipantRoles(response: HttpResponseBase): Observable<ParticipantRoleResponse[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ParticipantRoleResponse.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ParticipantRoleResponse[]>(<any>null);
    }

    /**
     * Get available courts
     * @return Success
     */
    getCourts(): Observable<CourtResponse[]> {
        let url_ = this.baseUrl + "/api/reference/courts";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCourts(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCourts(<any>response_);
                } catch (e) {
                    return <Observable<CourtResponse[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<CourtResponse[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetCourts(response: HttpResponseBase): Observable<CourtResponse[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CourtResponse.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = resultData404 ? ProblemDetails.fromJS(resultData404) : new ProblemDetails();
            return throwException("A server error occurred.", status, _responseText, _headers, result404);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CourtResponse[]>(<any>null);
    }

    /**
     * Get Judges
     * @return Success
     */
    getJudges(): Observable<ParticipantDetailsResponse[]> {
        let url_ = this.baseUrl + "/api/accounts/judges";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetJudges(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetJudges(<any>response_);
                } catch (e) {
                    return <Observable<ParticipantDetailsResponse[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<ParticipantDetailsResponse[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetJudges(response: HttpResponseBase): Observable<ParticipantDetailsResponse[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ParticipantDetailsResponse.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ParticipantDetailsResponse[]>(<any>null);
    }

    /**
     * @return Success
     */
    getUserProfile(): Observable<UserProfileResponse> {
        let url_ = this.baseUrl + "/api/user";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetUserProfile(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUserProfile(<any>response_);
                } catch (e) {
                    return <Observable<UserProfileResponse>><any>_observableThrow(e);
                }
            } else
                return <Observable<UserProfileResponse>><any>_observableThrow(response_);
        }));
    }

    protected processGetUserProfile(response: HttpResponseBase): Observable<UserProfileResponse> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? UserProfileResponse.fromJS(resultData200) : new UserProfileResponse();
            return _observableOf(result200);
            }));
        } else if (status === 401) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("A server error occurred.", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<UserProfileResponse>(<any>null);
    }
}

export class ChecklistsResponse implements IChecklistsResponse {
    /** Gets or sets check list for hearing and participant. */
    checklists?: HearingParticipantCheckListResponse[] | undefined;
    /** A list of hearings referenced by checklist responses in HearingsApi.Contract.Responses.ChecklistsResponse.Checklists. */
    hearings?: ChecklistsHearingResponse[] | undefined;
    /** Total number of items across all pages */
    total_count?: number | undefined;
    /** Maximum number of items returned in items */
    page_size?: number | undefined;
    /** The total number of pages given the current page size */
    total_pages?: number | undefined;
    /** Numbering of this paged response, starting from 1 */
    current_page?: number | undefined;
    /** Absolute url to the previous page of items.
            Will be null for the first page. */
    prev_page_url?: string | undefined;
    /** Absolute url for the next page of items.
            Will be null for the last page. */
    next_page_url?: string | undefined;

    constructor(data?: IChecklistsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["checklists"] && data["checklists"].constructor === Array) {
                this.checklists = [] as any;
                for (let item of data["checklists"])
                    this.checklists!.push(HearingParticipantCheckListResponse.fromJS(item));
            }
            if (data["hearings"] && data["hearings"].constructor === Array) {
                this.hearings = [] as any;
                for (let item of data["hearings"])
                    this.hearings!.push(ChecklistsHearingResponse.fromJS(item));
            }
            this.total_count = data["total_count"];
            this.page_size = data["page_size"];
            this.total_pages = data["total_pages"];
            this.current_page = data["current_page"];
            this.prev_page_url = data["prev_page_url"];
            this.next_page_url = data["next_page_url"];
        }
    }

    static fromJS(data: any): ChecklistsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ChecklistsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.checklists && this.checklists.constructor === Array) {
            data["checklists"] = [];
            for (let item of this.checklists)
                data["checklists"].push(item.toJSON());
        }
        if (this.hearings && this.hearings.constructor === Array) {
            data["hearings"] = [];
            for (let item of this.hearings)
                data["hearings"].push(item.toJSON());
        }
        data["total_count"] = this.total_count;
        data["page_size"] = this.page_size;
        data["total_pages"] = this.total_pages;
        data["current_page"] = this.current_page;
        data["prev_page_url"] = this.prev_page_url;
        data["next_page_url"] = this.next_page_url;
        return data; 
    }
}

export interface IChecklistsResponse {
    /** Gets or sets check list for hearing and participant. */
    checklists?: HearingParticipantCheckListResponse[] | undefined;
    /** A list of hearings referenced by checklist responses in HearingsApi.Contract.Responses.ChecklistsResponse.Checklists. */
    hearings?: ChecklistsHearingResponse[] | undefined;
    /** Total number of items across all pages */
    total_count?: number | undefined;
    /** Maximum number of items returned in items */
    page_size?: number | undefined;
    /** The total number of pages given the current page size */
    total_pages?: number | undefined;
    /** Numbering of this paged response, starting from 1 */
    current_page?: number | undefined;
    /** Absolute url to the previous page of items.
            Will be null for the first page. */
    prev_page_url?: string | undefined;
    /** Absolute url for the next page of items.
            Will be null for the last page. */
    next_page_url?: string | undefined;
}

export class HearingParticipantCheckListResponse implements IHearingParticipantCheckListResponse {
    hearing_id?: number | undefined;
    participant_id?: number | undefined;
    /** The participants title (i.e. Mr, Ms) */
    title?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    /** The participant role */
    role?: string | undefined;
    /** The date and time the checklist was submitted */
    completed_date?: Date | undefined;
    /** Checklist answers submitted */
    question_answer_responses?: QuestionAnswerResponse[] | undefined;
    /** Landline number to the participant */
    landline?: string | undefined;
    /** Mobile phone number to the participant */
    mobile?: string | undefined;

    constructor(data?: IHearingParticipantCheckListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.hearing_id = data["hearing_id"];
            this.participant_id = data["participant_id"];
            this.title = data["title"];
            this.first_name = data["first_name"];
            this.last_name = data["last_name"];
            this.role = data["role"];
            this.completed_date = data["completed_date"] ? new Date(data["completed_date"].toString()) : <any>undefined;
            if (data["question_answer_responses"] && data["question_answer_responses"].constructor === Array) {
                this.question_answer_responses = [] as any;
                for (let item of data["question_answer_responses"])
                    this.question_answer_responses!.push(QuestionAnswerResponse.fromJS(item));
            }
            this.landline = data["landline"];
            this.mobile = data["mobile"];
        }
    }

    static fromJS(data: any): HearingParticipantCheckListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HearingParticipantCheckListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["hearing_id"] = this.hearing_id;
        data["participant_id"] = this.participant_id;
        data["title"] = this.title;
        data["first_name"] = this.first_name;
        data["last_name"] = this.last_name;
        data["role"] = this.role;
        data["completed_date"] = this.completed_date ? this.completed_date.toISOString() : <any>undefined;
        if (this.question_answer_responses && this.question_answer_responses.constructor === Array) {
            data["question_answer_responses"] = [];
            for (let item of this.question_answer_responses)
                data["question_answer_responses"].push(item.toJSON());
        }
        data["landline"] = this.landline;
        data["mobile"] = this.mobile;
        return data; 
    }
}

export interface IHearingParticipantCheckListResponse {
    hearing_id?: number | undefined;
    participant_id?: number | undefined;
    /** The participants title (i.e. Mr, Ms) */
    title?: string | undefined;
    first_name?: string | undefined;
    last_name?: string | undefined;
    /** The participant role */
    role?: string | undefined;
    /** The date and time the checklist was submitted */
    completed_date?: Date | undefined;
    /** Checklist answers submitted */
    question_answer_responses?: QuestionAnswerResponse[] | undefined;
    /** Landline number to the participant */
    landline?: string | undefined;
    /** Mobile phone number to the participant */
    mobile?: string | undefined;
}

/** Hearing information for participant checklists */
export class ChecklistsHearingResponse implements IChecklistsHearingResponse {
    hearing_id?: number | undefined;
    scheduled_date_time?: Date | undefined;
    status?: string | undefined;
    cases?: CaseResponse[] | undefined;

    constructor(data?: IChecklistsHearingResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.hearing_id = data["hearing_id"];
            this.scheduled_date_time = data["scheduled_date_time"] ? new Date(data["scheduled_date_time"].toString()) : <any>undefined;
            this.status = data["status"];
            if (data["cases"] && data["cases"].constructor === Array) {
                this.cases = [] as any;
                for (let item of data["cases"])
                    this.cases!.push(CaseResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ChecklistsHearingResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ChecklistsHearingResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["hearing_id"] = this.hearing_id;
        data["scheduled_date_time"] = this.scheduled_date_time ? this.scheduled_date_time.toISOString() : <any>undefined;
        data["status"] = this.status;
        if (this.cases && this.cases.constructor === Array) {
            data["cases"] = [];
            for (let item of this.cases)
                data["cases"].push(item.toJSON());
        }
        return data; 
    }
}

/** Hearing information for participant checklists */
export interface IChecklistsHearingResponse {
    hearing_id?: number | undefined;
    scheduled_date_time?: Date | undefined;
    status?: string | undefined;
    cases?: CaseResponse[] | undefined;
}

export class QuestionAnswerResponse implements IQuestionAnswerResponse {
    question_key?: string | undefined;
    answer?: string | undefined;
    notes?: string | undefined;
    created_at?: Date | undefined;

    constructor(data?: IQuestionAnswerResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.question_key = data["question_key"];
            this.answer = data["answer"];
            this.notes = data["notes"];
            this.created_at = data["created_at"] ? new Date(data["created_at"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): QuestionAnswerResponse {
        data = typeof data === 'object' ? data : {};
        let result = new QuestionAnswerResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["question_key"] = this.question_key;
        data["answer"] = this.answer;
        data["notes"] = this.notes;
        data["created_at"] = this.created_at ? this.created_at.toISOString() : <any>undefined;
        return data; 
    }
}

export interface IQuestionAnswerResponse {
    question_key?: string | undefined;
    answer?: string | undefined;
    notes?: string | undefined;
    created_at?: Date | undefined;
}

export class CaseResponse implements ICaseResponse {
    /** The case number */
    number?: string | undefined;
    /** The case name */
    name?: string | undefined;

    constructor(data?: ICaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.number = data["number"];
            this.name = data["name"];
        }
    }

    static fromJS(data: any): CaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["number"] = this.number;
        data["name"] = this.name;
        return data; 
    }
}

export interface ICaseResponse {
    /** The case number */
    number?: string | undefined;
    /** The case name */
    name?: string | undefined;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.type = data["type"];
            this.title = data["title"];
            this.status = data["status"];
            this.detail = data["detail"];
            this.instance = data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data; 
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

/** Configuration to initialise the UI application */
export class ClientSettingsResponse implements IClientSettingsResponse {
    /** The Azure Tenant Id */
    tenant_id?: string | undefined;
    /** The UI Client Id */
    client_id?: string | undefined;
    /** The Uri to redirect back to after a successful login */
    redirect_uri?: string | undefined;
    /** The Uri to redirect back to after a successful logout */
    post_logout_redirect_uri?: string | undefined;
    /** The Application Insight Instrumentation Key */
    instrumentation_key?: string | undefined;

    constructor(data?: IClientSettingsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.tenant_id = data["tenant_id"];
            this.client_id = data["client_id"];
            this.redirect_uri = data["redirect_uri"];
            this.post_logout_redirect_uri = data["post_logout_redirect_uri"];
            this.instrumentation_key = data["instrumentation_key"];
        }
    }

    static fromJS(data: any): ClientSettingsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ClientSettingsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["tenant_id"] = this.tenant_id;
        data["client_id"] = this.client_id;
        data["redirect_uri"] = this.redirect_uri;
        data["post_logout_redirect_uri"] = this.post_logout_redirect_uri;
        data["instrumentation_key"] = this.instrumentation_key;
        return data; 
    }
}

/** Configuration to initialise the UI application */
export interface IClientSettingsResponse {
    /** The Azure Tenant Id */
    tenant_id?: string | undefined;
    /** The UI Client Id */
    client_id?: string | undefined;
    /** The Uri to redirect back to after a successful login */
    redirect_uri?: string | undefined;
    /** The Uri to redirect back to after a successful logout */
    post_logout_redirect_uri?: string | undefined;
    /** The Application Insight Instrumentation Key */
    instrumentation_key?: string | undefined;
}

/** Hearing Request Object */
export class HearingRequest implements IHearingRequest {
    /** Hearing Schedule Date and Time */
    scheduled_date_time?: Date | undefined;
    /** Duration of the hearing */
    scheduled_duration?: number | undefined;
    /** Hearing Type Id */
    hearing_type_id?: number | undefined;
    /** Hearing Medium Id */
    hearing_medium_id?: number | undefined;
    /** Court Id where hearing will take place */
    court_id?: number | undefined;
    /** Associated Case */
    cases?: CaseRequest[] | undefined;
    /** List of related feeds for the hearing */
    feeds?: FeedRequest[] | undefined;
    /** User booking the hearing */
    created_by?: string | undefined;

    constructor(data?: IHearingRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.scheduled_date_time = data["scheduled_date_time"] ? new Date(data["scheduled_date_time"].toString()) : <any>undefined;
            this.scheduled_duration = data["scheduled_duration"];
            this.hearing_type_id = data["hearing_type_id"];
            this.hearing_medium_id = data["hearing_medium_id"];
            this.court_id = data["court_id"];
            if (data["cases"] && data["cases"].constructor === Array) {
                this.cases = [] as any;
                for (let item of data["cases"])
                    this.cases!.push(CaseRequest.fromJS(item));
            }
            if (data["feeds"] && data["feeds"].constructor === Array) {
                this.feeds = [] as any;
                for (let item of data["feeds"])
                    this.feeds!.push(FeedRequest.fromJS(item));
            }
            this.created_by = data["created_by"];
        }
    }

    static fromJS(data: any): HearingRequest {
        data = typeof data === 'object' ? data : {};
        let result = new HearingRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["scheduled_date_time"] = this.scheduled_date_time ? this.scheduled_date_time.toISOString() : <any>undefined;
        data["scheduled_duration"] = this.scheduled_duration;
        data["hearing_type_id"] = this.hearing_type_id;
        data["hearing_medium_id"] = this.hearing_medium_id;
        data["court_id"] = this.court_id;
        if (this.cases && this.cases.constructor === Array) {
            data["cases"] = [];
            for (let item of this.cases)
                data["cases"].push(item.toJSON());
        }
        if (this.feeds && this.feeds.constructor === Array) {
            data["feeds"] = [];
            for (let item of this.feeds)
                data["feeds"].push(item.toJSON());
        }
        data["created_by"] = this.created_by;
        return data; 
    }
}

/** Hearing Request Object */
export interface IHearingRequest {
    /** Hearing Schedule Date and Time */
    scheduled_date_time?: Date | undefined;
    /** Duration of the hearing */
    scheduled_duration?: number | undefined;
    /** Hearing Type Id */
    hearing_type_id?: number | undefined;
    /** Hearing Medium Id */
    hearing_medium_id?: number | undefined;
    /** Court Id where hearing will take place */
    court_id?: number | undefined;
    /** Associated Case */
    cases?: CaseRequest[] | undefined;
    /** List of related feeds for the hearing */
    feeds?: FeedRequest[] | undefined;
    /** User booking the hearing */
    created_by?: string | undefined;
}

export class CaseRequest implements ICaseRequest {
    /** Case Number */
    number?: string | undefined;
    /** Case Name */
    name?: string | undefined;

    constructor(data?: ICaseRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.number = data["number"];
            this.name = data["name"];
        }
    }

    static fromJS(data: any): CaseRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CaseRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["number"] = this.number;
        data["name"] = this.name;
        return data; 
    }
}

export interface ICaseRequest {
    /** Case Number */
    number?: string | undefined;
    /** Case Name */
    name?: string | undefined;
}

/** Feed Request Object */
export class FeedRequest implements IFeedRequest {
    /** Hearing Location */
    location?: string | undefined;
    /** List of participants in that particular location */
    participants?: ParticipantRequest[] | undefined;

    constructor(data?: IFeedRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.location = data["location"];
            if (data["participants"] && data["participants"].constructor === Array) {
                this.participants = [] as any;
                for (let item of data["participants"])
                    this.participants!.push(ParticipantRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FeedRequest {
        data = typeof data === 'object' ? data : {};
        let result = new FeedRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["location"] = this.location;
        if (this.participants && this.participants.constructor === Array) {
            data["participants"] = [];
            for (let item of this.participants)
                data["participants"].push(item.toJSON());
        }
        return data; 
    }
}

/** Feed Request Object */
export interface IFeedRequest {
    /** Hearing Location */
    location?: string | undefined;
    /** List of participants in that particular location */
    participants?: ParticipantRequest[] | undefined;
}

/** Participant class */
export class ParticipantRequest implements IParticipantRequest {
    /** Participant */
    title?: string | undefined;
    /** Participant FirstName */
    first_name?: string | undefined;
    /** Participant Last Name */
    last_name?: string | undefined;
    /** Participant MiddleNames */
    middle_names?: string | undefined;
    /** Participant Diaply Name */
    display_name?: string | undefined;
    /** Participant Username (HMCTS login) */
    username?: string | undefined;
    /** Participant Email Address */
    email?: string | undefined;
    /** Participant External Id If Participant is an external participant */
    external_id?: string | undefined;
    /** Set to true If Participant is an external participant */
    external_flag?: boolean | undefined;
    /** Participant Role */
    role?: string | undefined;
    /** Participant Phone Number */
    phone?: string | undefined;
    /** Participant Mobile Phone Number */
    mobile?: string | undefined;
    /** Participant representing behalf of */
    representing?: string | undefined;
    /** Participant Organisation Name */
    organisation_name?: string | undefined;
    /** Participant Organisation Address */
    organisation_address?: string | undefined;

    constructor(data?: IParticipantRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.title = data["title"];
            this.first_name = data["first_name"];
            this.last_name = data["last_name"];
            this.middle_names = data["middle_names"];
            this.display_name = data["display_name"];
            this.username = data["username"];
            this.email = data["email"];
            this.external_id = data["external_id"];
            this.external_flag = data["external_flag"];
            this.role = data["role"];
            this.phone = data["phone"];
            this.mobile = data["mobile"];
            this.representing = data["representing"];
            this.organisation_name = data["organisation_name"];
            this.organisation_address = data["organisation_address"];
        }
    }

    static fromJS(data: any): ParticipantRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ParticipantRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["first_name"] = this.first_name;
        data["last_name"] = this.last_name;
        data["middle_names"] = this.middle_names;
        data["display_name"] = this.display_name;
        data["username"] = this.username;
        data["email"] = this.email;
        data["external_id"] = this.external_id;
        data["external_flag"] = this.external_flag;
        data["role"] = this.role;
        data["phone"] = this.phone;
        data["mobile"] = this.mobile;
        data["representing"] = this.representing;
        data["organisation_name"] = this.organisation_name;
        data["organisation_address"] = this.organisation_address;
        return data; 
    }
}

/** Participant class */
export interface IParticipantRequest {
    /** Participant */
    title?: string | undefined;
    /** Participant FirstName */
    first_name?: string | undefined;
    /** Participant Last Name */
    last_name?: string | undefined;
    /** Participant MiddleNames */
    middle_names?: string | undefined;
    /** Participant Diaply Name */
    display_name?: string | undefined;
    /** Participant Username (HMCTS login) */
    username?: string | undefined;
    /** Participant Email Address */
    email?: string | undefined;
    /** Participant External Id If Participant is an external participant */
    external_id?: string | undefined;
    /** Set to true If Participant is an external participant */
    external_flag?: boolean | undefined;
    /** Participant Role */
    role?: string | undefined;
    /** Participant Phone Number */
    phone?: string | undefined;
    /** Participant Mobile Phone Number */
    mobile?: string | undefined;
    /** Participant representing behalf of */
    representing?: string | undefined;
    /** Participant Organisation Name */
    organisation_name?: string | undefined;
    /** Participant Organisation Address */
    organisation_address?: string | undefined;
}

export class BookingsResponse implements IBookingsResponse {
    /** Gets or sets list of bookings hearings. */
    hearings?: BookingsByDateResponse[] | undefined;
    /** Gets or sets a unique sequential value to get next set of records. 
            value is set to 0 if no records to return. */
    next_cursor?: string | undefined;
    /** Gets or sets the maximum number of items returned for the page. */
    limit?: number | undefined;
    /** Absolute url to the previous page of items.
            Will be null for the first page. */
    prev_page_url?: string | undefined;
    /** Absolute url for the next page of items.
            Will be null for the last page. */
    next_page_url?: string | undefined;

    constructor(data?: IBookingsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            if (data["hearings"] && data["hearings"].constructor === Array) {
                this.hearings = [] as any;
                for (let item of data["hearings"])
                    this.hearings!.push(BookingsByDateResponse.fromJS(item));
            }
            this.next_cursor = data["next_cursor"];
            this.limit = data["limit"];
            this.prev_page_url = data["prev_page_url"];
            this.next_page_url = data["next_page_url"];
        }
    }

    static fromJS(data: any): BookingsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BookingsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.hearings && this.hearings.constructor === Array) {
            data["hearings"] = [];
            for (let item of this.hearings)
                data["hearings"].push(item.toJSON());
        }
        data["next_cursor"] = this.next_cursor;
        data["limit"] = this.limit;
        data["prev_page_url"] = this.prev_page_url;
        data["next_page_url"] = this.next_page_url;
        return data; 
    }
}

export interface IBookingsResponse {
    /** Gets or sets list of bookings hearings. */
    hearings?: BookingsByDateResponse[] | undefined;
    /** Gets or sets a unique sequential value to get next set of records. 
            value is set to 0 if no records to return. */
    next_cursor?: string | undefined;
    /** Gets or sets the maximum number of items returned for the page. */
    limit?: number | undefined;
    /** Absolute url to the previous page of items.
            Will be null for the first page. */
    prev_page_url?: string | undefined;
    /** Absolute url for the next page of items.
            Will be null for the last page. */
    next_page_url?: string | undefined;
}

export class BookingsByDateResponse implements IBookingsByDateResponse {
    /** The hearings grouped by date without time. */
    scheduled_date?: Date | undefined;
    /** Gets or sets list of bookings hearings. */
    hearings?: BookingsHearingResponse[] | undefined;

    constructor(data?: IBookingsByDateResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.scheduled_date = data["scheduled_date"] ? new Date(data["scheduled_date"].toString()) : <any>undefined;
            if (data["hearings"] && data["hearings"].constructor === Array) {
                this.hearings = [] as any;
                for (let item of data["hearings"])
                    this.hearings!.push(BookingsHearingResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BookingsByDateResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BookingsByDateResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["scheduled_date"] = this.scheduled_date ? this.scheduled_date.toISOString() : <any>undefined;
        if (this.hearings && this.hearings.constructor === Array) {
            data["hearings"] = [];
            for (let item of this.hearings)
                data["hearings"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IBookingsByDateResponse {
    /** The hearings grouped by date without time. */
    scheduled_date?: Date | undefined;
    /** Gets or sets list of bookings hearings. */
    hearings?: BookingsHearingResponse[] | undefined;
}

export class BookingsHearingResponse implements IBookingsHearingResponse {
    /** Gets or sets the hearing ID. */
    hearing_id?: number | undefined;
    /** Gets or sets the hearing number/reference. */
    hearing_number?: string | undefined;
    /** Gets or sets the hearing title/name. */
    hearing_name?: string | undefined;
    /** Gets or sets the hearing scheduled date and time. */
    scheduled_date_time?: Date | undefined;
    /** Gets or sets the hearing duration. */
    scheduled_duration?: number | undefined;
    /** Gets or sets the hearing case type. */
    hearing_type_name?: string | undefined;
    /** Gets or sets the cour room. */
    court_room?: string | undefined;
    /** Gets or sets the court address. */
    court_address?: string | undefined;
    /** Gets or sets Judge name. */
    judge_name?: string | undefined;
    /** Gets or sets the name/email person who create the hearing. */
    created_by?: string | undefined;
    /** Gets or sets the created date of hearing. */
    created_date?: Date | undefined;
    /** Gets or sets the name/email person who last edit the hearing. */
    last_edit_by?: string | undefined;
    /** Gets or sets the last edited date of hearing. */
    last_edit_date?: Date | undefined;
    /** Gets the scheduled date without time. */
    hearing_date?: Date | undefined;

    constructor(data?: IBookingsHearingResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.hearing_id = data["hearing_id"];
            this.hearing_number = data["hearing_number"];
            this.hearing_name = data["hearing_name"];
            this.scheduled_date_time = data["scheduled_date_time"] ? new Date(data["scheduled_date_time"].toString()) : <any>undefined;
            this.scheduled_duration = data["scheduled_duration"];
            this.hearing_type_name = data["hearing_type_name"];
            this.court_room = data["court_room"];
            this.court_address = data["court_address"];
            this.judge_name = data["judge_name"];
            this.created_by = data["created_by"];
            this.created_date = data["created_date"] ? new Date(data["created_date"].toString()) : <any>undefined;
            this.last_edit_by = data["last_edit_by"];
            this.last_edit_date = data["last_edit_date"] ? new Date(data["last_edit_date"].toString()) : <any>undefined;
            this.hearing_date = data["hearing_date"] ? new Date(data["hearing_date"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): BookingsHearingResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BookingsHearingResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["hearing_id"] = this.hearing_id;
        data["hearing_number"] = this.hearing_number;
        data["hearing_name"] = this.hearing_name;
        data["scheduled_date_time"] = this.scheduled_date_time ? this.scheduled_date_time.toISOString() : <any>undefined;
        data["scheduled_duration"] = this.scheduled_duration;
        data["hearing_type_name"] = this.hearing_type_name;
        data["court_room"] = this.court_room;
        data["court_address"] = this.court_address;
        data["judge_name"] = this.judge_name;
        data["created_by"] = this.created_by;
        data["created_date"] = this.created_date ? this.created_date.toISOString() : <any>undefined;
        data["last_edit_by"] = this.last_edit_by;
        data["last_edit_date"] = this.last_edit_date ? this.last_edit_date.toISOString() : <any>undefined;
        data["hearing_date"] = this.hearing_date ? this.hearing_date.toISOString() : <any>undefined;
        return data; 
    }
}

export interface IBookingsHearingResponse {
    /** Gets or sets the hearing ID. */
    hearing_id?: number | undefined;
    /** Gets or sets the hearing number/reference. */
    hearing_number?: string | undefined;
    /** Gets or sets the hearing title/name. */
    hearing_name?: string | undefined;
    /** Gets or sets the hearing scheduled date and time. */
    scheduled_date_time?: Date | undefined;
    /** Gets or sets the hearing duration. */
    scheduled_duration?: number | undefined;
    /** Gets or sets the hearing case type. */
    hearing_type_name?: string | undefined;
    /** Gets or sets the cour room. */
    court_room?: string | undefined;
    /** Gets or sets the court address. */
    court_address?: string | undefined;
    /** Gets or sets Judge name. */
    judge_name?: string | undefined;
    /** Gets or sets the name/email person who create the hearing. */
    created_by?: string | undefined;
    /** Gets or sets the created date of hearing. */
    created_date?: Date | undefined;
    /** Gets or sets the name/email person who last edit the hearing. */
    last_edit_by?: string | undefined;
    /** Gets or sets the last edited date of hearing. */
    last_edit_date?: Date | undefined;
    /** Gets the scheduled date without time. */
    hearing_date?: Date | undefined;
}

export class HearingTypeResponse implements IHearingTypeResponse {
    code?: string | undefined;
    group?: string | undefined;
    id?: number | undefined;
    name?: string | undefined;

    constructor(data?: IHearingTypeResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.code = data["code"];
            this.group = data["group"];
            this.id = data["id"];
            this.name = data["name"];
        }
    }

    static fromJS(data: any): HearingTypeResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HearingTypeResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["group"] = this.group;
        data["id"] = this.id;
        data["name"] = this.name;
        return data; 
    }
}

export interface IHearingTypeResponse {
    code?: string | undefined;
    group?: string | undefined;
    id?: number | undefined;
    name?: string | undefined;
}

export class HearingMediumResponse implements IHearingMediumResponse {
    id?: number | undefined;
    name?: string | undefined;

    constructor(data?: IHearingMediumResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
        }
    }

    static fromJS(data: any): HearingMediumResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HearingMediumResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data; 
    }
}

export interface IHearingMediumResponse {
    id?: number | undefined;
    name?: string | undefined;
}

/** Participant Role Response */
export class ParticipantRoleResponse implements IParticipantRoleResponse {
    /** The name of the role */
    name?: string | undefined;

    constructor(data?: IParticipantRoleResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.name = data["name"];
        }
    }

    static fromJS(data: any): ParticipantRoleResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ParticipantRoleResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data; 
    }
}

/** Participant Role Response */
export interface IParticipantRoleResponse {
    /** The name of the role */
    name?: string | undefined;
}

/** Court Response */
export class CourtResponse implements ICourtResponse {
    /** Court ID */
    id?: number | undefined;
    /** Court room */
    room?: string | undefined;
    /** Court address */
    address?: string | undefined;

    constructor(data?: ICourtResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.room = data["room"];
            this.address = data["address"];
        }
    }

    static fromJS(data: any): CourtResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CourtResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["room"] = this.room;
        data["address"] = this.address;
        return data; 
    }
}

/** Court Response */
export interface ICourtResponse {
    /** Court ID */
    id?: number | undefined;
    /** Court room */
    room?: string | undefined;
    /** Court address */
    address?: string | undefined;
}

export class ParticipantDetailsResponse implements IParticipantDetailsResponse {
    id?: string | undefined;
    title?: string | undefined;
    first_name?: string | undefined;
    middle_name?: string | undefined;
    last_name?: string | undefined;
    display_name?: string | undefined;
    email?: string | undefined;
    role?: string | undefined;
    phone?: string | undefined;

    constructor(data?: IParticipantDetailsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.title = data["title"];
            this.first_name = data["first_name"];
            this.middle_name = data["middle_name"];
            this.last_name = data["last_name"];
            this.display_name = data["display_name"];
            this.email = data["email"];
            this.role = data["role"];
            this.phone = data["phone"];
        }
    }

    static fromJS(data: any): ParticipantDetailsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ParticipantDetailsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["first_name"] = this.first_name;
        data["middle_name"] = this.middle_name;
        data["last_name"] = this.last_name;
        data["display_name"] = this.display_name;
        data["email"] = this.email;
        data["role"] = this.role;
        data["phone"] = this.phone;
        return data; 
    }
}

export interface IParticipantDetailsResponse {
    id?: string | undefined;
    title?: string | undefined;
    first_name?: string | undefined;
    middle_name?: string | undefined;
    last_name?: string | undefined;
    display_name?: string | undefined;
    email?: string | undefined;
    role?: string | undefined;
    phone?: string | undefined;
}

export class UserProfileResponse implements IUserProfileResponse {
    is_vh_officer_administrator_role?: boolean | undefined;
    is_case_administrator?: boolean | undefined;

    constructor(data?: IUserProfileResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.is_vh_officer_administrator_role = data["is_vh_officer_administrator_role"];
            this.is_case_administrator = data["is_case_administrator"];
        }
    }

    static fromJS(data: any): UserProfileResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserProfileResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["is_vh_officer_administrator_role"] = this.is_vh_officer_administrator_role;
        data["is_case_administrator"] = this.is_case_administrator;
        return data; 
    }
}

export interface IUserProfileResponse {
    is_vh_officer_administrator_role?: boolean | undefined;
    is_case_administrator?: boolean | undefined;
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if(result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}