export let PageUrls = {
  PageNotFound: '/page-not-found',
  Unauthorised: '/unauthorised',
  ServiceProblem: '/error',
  Dashboard: '/dashboard',
  CreateHearing: '/book-hearing',
  HearingSchedule: '/hearing-schedule',
  AssignJudge: '/assign-judge',
  AddParticipants: '/add-participants',
  Endpoints: '/endpoints',
  OtherInformation: '/other-information',
  Summary: '/summary',
  BookingConfirmation: '/booking-confirmation',
  BookingsList: '/bookings-list',
  BookingDetails: '/booking-details',
};
