export let PageUrls = {
    PageNotFound: '/page-not-found',
    Unauthorised: '/unauthorised',
    ServiceProblem: '/error',
    Dashboard: '/dashboard',
    CreateHearing: '/book-hearing',
    HearingSchedule: '/hearing-schedule',
    AssignJudge: '/assign-judge',
    AddParticipants: '/add-participants',
    Endpoints: '/video-access-points',
    OtherInformation: '/other-information',
    Summary: '/summary',
    BookingConfirmation: '/booking-confirmation',
    BookingsList: '/bookings-list',
    BookingDetails: '/booking-details',
    DeleteParticipant: '/delete-participant',
    EditParticipantSearch: '/edit-participant-search',
    EditParticipant: '/edit-participant',
    Login: '/login',
    JoinLink: '/quickjoin'
};
