export const Constants = {
  BookHearingTitle: 'Book a video hearing',
  PleaseSelect: 'Please Select',
  Solicitor: 'Solicitor',
  PleaseSelectPattern: '^((?!Please Select).)*$',
  Judge: 'Judge',
  Citizen: 'Citizen',
  Professional: 'Professional',
  Error: {
    RoleErrorMsg: 'Please select a role',
    PartyErrorMsg: 'Please select a party',
    EmailErrorMsg: 'Please enter a valid email address',
    TitleErrorMsg: 'Please select a title',
    FirstNameErrorMsg: 'Please enter a first name',
    LastNameErrorMsg: 'Please enter a last name',
    PhoneErrorMsg: 'Please enter a valid telephone number',
    NoParticipantsErrorMsg: 'Please enter at least one participant',
    HouseNumberErrorMsg: 'Please enter a building number',
    StreetErrorMsg: 'Please enter a street name',
    CityErrorMsg: 'Please enter a town or city',
    CountyErrorMsg: 'Please enter a county',
    PostcodeErrorMsg: 'Please enter a postcode',
  },
  Contact: {
    phone: '0300 303 0655',
    email: 'admin@videohearings.hmcts.net'
  },
  IndividualRoles: ['Claimant LIP', 'Defendant LIP', 'Applicant LIP', 'Respondent LIP'],
  bookingHasChangesKey: 'bookingHasChangesKey',
  bookingEditKey: 'bookingEditKey',
};
