//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("2.3.1.0")]
[assembly: AssemblyVersion("2.3.1.0")]
[assembly: AssemblyInformationalVersion("2.3.1-VIH-11026---Display-app-version.1+701.Branch.VIH-11026---Display-app-version.Sha.f89a9fdce082997c7dc52d4188964a8ad2a25099")]