---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  disableTraefikTls: false
  environment:
    AZUREAD__POSTLOGOUTREDIRECTURI: https://${SERVICE_FQDN}/logout
    AZUREAD__REDIRECTURI: https://${SERVICE_FQDN}/home
    VHSERVICES__VIDEOWEBURL: https://${SERVICE_FQDN}
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-632.platform.hmcts.net/