---
java:
  image: "${IMAGE_NAME}"
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  disableTraefikTls: false
  environment:
    AZUREAD__POSTLOGOUTREDIRECTURI: https://${SERVICE_FQDN}/logout
    AZUREAD__REDIRECTURI: https://${SERVICE_FQDN}/home
    DOM1__POSTLOGOUTREDIRECTURI: https://${SERVICE_FQDN}/logout
    DOM1__REDIRECTURI: https://${SERVICE_FQDN}/home
    VHSERVICES__BOOKINGSAPIURL: https://vh-bookings-api-pr-909.dev.platform.hmcts.net/