#error Parsing error near 'import { element, by, ElementFinder } from '
#error Parsing error near 'import { Helpers } from '
#error Parsing error near 'import { LocatorHelpers } from '
#error Parsing error near 'export class ParticipantPageObject {'
#error Parsing error near 'private participantBreadcrumb = element(by.xpath('
#error Parsing error near 'private participantPageTitle = element(by.xpath('